// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.RazorWeb.Data;

#nullable disable

namespace OrderManagement.RazorWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429071722_FixAgentIDRelationship")]
    partial class FixAgentIDRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Agent", b =>
                {
                    b.Property<int>("AgentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AgentID");

                    b.ToTable("Agent", (string)null);

                    b.HasData(
                        new
                        {
                            AgentID = -1,
                            Address = "123 Main St",
                            AgentName = "Agent Smith",
                            ContactNumber = "555-1234",
                            Email = "agent.smith@example.com"
                        },
                        new
                        {
                            AgentID = -2,
                            Address = "456 Oak Ave",
                            AgentName = "Agent Jones",
                            ContactNumber = "555-5678",
                            Email = "agent.jones@example.com"
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ItemID");

                    b.ToTable("Item", (string)null);

                    b.HasData(
                        new
                        {
                            ItemID = -1,
                            ItemName = "Laptop",
                            Size = "15-inch",
                            StockQuantity = 50,
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            ItemID = -2,
                            ItemName = "Smartphone",
                            Size = "6-inch",
                            StockQuantity = 100,
                            UnitPrice = 699.99m
                        },
                        new
                        {
                            ItemID = -3,
                            ItemName = "Headphones",
                            Size = "Over-ear",
                            StockQuantity = 200,
                            UnitPrice = 89.99m
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("AgentID")
                        .HasColumnType("int");

                    b.Property<int?>("AgentID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderID");

                    b.HasIndex("AgentID");

                    b.HasIndex("AgentID1");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            OrderID = -1,
                            AgentID = -1,
                            OrderDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 150.00m
                        },
                        new
                        {
                            OrderID = -2,
                            AgentID = -2,
                            OrderDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalAmount = 275.50m
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemID1")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemID");

                    b.HasIndex("ItemID1");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetail", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ID = 0,
                            ItemID = -1,
                            OrderID = -1,
                            Quantity = 2,
                            TotalAmount = 100.00m,
                            UnitAmount = 50.00m
                        },
                        new
                        {
                            Id = -2,
                            ID = 0,
                            ItemID = -3,
                            OrderID = -1,
                            Quantity = 1,
                            TotalAmount = 50.00m,
                            UnitAmount = 50.00m
                        },
                        new
                        {
                            Id = -3,
                            ID = 0,
                            ItemID = -2,
                            OrderID = -2,
                            Quantity = 1,
                            TotalAmount = 275.50m,
                            UnitAmount = 275.50m
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            IsLocked = false,
                            Password = "password",
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            IsLocked = false,
                            Password = "user123",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Order", b =>
                {
                    b.HasOne("OrderManagement.RazorWeb.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Agent_AgentID");

                    b.HasOne("OrderManagement.RazorWeb.Models.Agent", null)
                        .WithMany("Orders")
                        .HasForeignKey("AgentID1");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.OrderDetail", b =>
                {
                    b.HasOne("OrderManagement.RazorWeb.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.RazorWeb.Models.Item", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("ItemID1");

                    b.HasOne("OrderManagement.RazorWeb.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Agent", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Item", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
