// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.RazorWeb.Data;

#nullable disable

namespace OrderManagement.RazorWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250427223358_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AgentID")
                        .HasColumnType("int");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            AgentID = 0,
                            AgentName = "Agent Smith",
                            ContactNumber = "555-1234",
                            Email = "agent.smith@example.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            AgentID = 0,
                            AgentName = "Agent Jones",
                            ContactNumber = "555-5678",
                            Email = "agent.jones@example.com"
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Id = 0,
                            ItemName = "Item 1",
                            Price = 0m,
                            Size = "Large",
                            StockQuantity = 50,
                            UnitPrice = 10.99m
                        },
                        new
                        {
                            ItemID = 2,
                            Id = 0,
                            ItemName = "Item 2",
                            Price = 0m,
                            Size = "Medium",
                            StockQuantity = 30,
                            UnitPrice = 9.99m
                        },
                        new
                        {
                            ItemID = 3,
                            Id = 0,
                            ItemName = "Item 3",
                            Price = 0m,
                            Size = "Small",
                            StockQuantity = 20,
                            UnitPrice = 12.99m
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("AgentID")
                        .HasColumnType("int");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderID");

                    b.HasIndex("AgentID");

                    b.HasIndex("AgentId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            AgentID = 1,
                            CustomerName = "John Doe",
                            OrderDate = new DateTime(2025, 4, 23, 5, 33, 58, 19, DateTimeKind.Local).AddTicks(6462),
                            Status = "Completed",
                            Total = 150.00m,
                            TotalAmount = 150.00m
                        },
                        new
                        {
                            OrderID = 2,
                            AgentID = 2,
                            CustomerName = "Jane Smith",
                            OrderDate = new DateTime(2025, 4, 26, 5, 33, 58, 20, DateTimeKind.Local).AddTicks(8203),
                            Status = "Pending",
                            Total = 275.50m,
                            TotalAmount = 275.50m
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemID1")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemID");

                    b.HasIndex("ItemID1");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ID = 0,
                            ItemID = 1,
                            OrderID = 1,
                            Quantity = 2,
                            TotalAmount = 100.00m,
                            UnitAmount = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            ID = 0,
                            ItemID = 2,
                            OrderID = 1,
                            Quantity = 1,
                            TotalAmount = 50.00m,
                            UnitAmount = 50.00m
                        },
                        new
                        {
                            Id = 3,
                            ID = 0,
                            ItemID = 3,
                            OrderID = 2,
                            Quantity = 3,
                            TotalAmount = 275.50m,
                            UnitAmount = 91.83m
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            IsLocked = false,
                            Password = "password",
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            IsLocked = false,
                            Password = "user123",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Order", b =>
                {
                    b.HasOne("OrderManagement.RazorWeb.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.RazorWeb.Models.Agent", null)
                        .WithMany("Orders")
                        .HasForeignKey("AgentId");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.OrderDetail", b =>
                {
                    b.HasOne("OrderManagement.RazorWeb.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.RazorWeb.Models.Item", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("ItemID1");

                    b.HasOne("OrderManagement.RazorWeb.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Agent", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Item", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("OrderManagement.RazorWeb.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
